# Generated by Django 5.2.6 on 2025-09-15 23:36

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={
                "ordering": ("user__username",),
                "verbose_name": "Perfil GCM",
                "verbose_name_plural": "Perfis GCM",
            },
        ),
        migrations.AddField(
            model_name="perfil",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="classe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3C", "3ª Classe"),
                    ("2C", "2ª Classe"),
                    ("1C", "1ª Classe"),
                    ("CD", "Classe Distinta"),
                    ("CE", "Classe Especial"),
                    ("SUB", "Subinspetor"),
                    ("INS", "Inspetor"),
                    ("SCM", "Sub CMT"),
                    ("CMT", "CMT"),
                ],
                max_length=3,
                verbose_name="Classe",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="assinatura_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.assinatura_upload_to,
                verbose_name="Assinatura (PNG/JPG)",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cargo",
            field=models.CharField(
                default="Guarda Civil Municipal", max_length=80, verbose_name="Cargo"
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="equipe",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
                verbose_name="Equipe",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="matricula",
            field=models.CharField(blank=True, max_length=20, verbose_name="Matrícula"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
