# Generated by Django 5.2.6 on 2025-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfil_options_perfil_ativo_perfil_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='assinatura_digital',
            field=models.TextField(blank=True, help_text='Assinatura desenhada digitalmente', verbose_name='Assinatura Digital (Base64)'),
        ),
    ]
