# Generated by Django 5.2.6 on 2025-10-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_assinatura_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(blank=True, db_index=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['sigla'], name='users_lotac_sigla_e2faa8_idx')],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='users.lotacao'),
        ),
    ]
