# Generated by Django 5.2.6 on 2025-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lotacao_perfil_lotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='E-mail usado para recuperar a senha (opcional).', max_length=254, verbose_name='Email de recuperação'),
        ),
    ]
