# Generated by Django 5.2.6 on 2025-09-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('vitima_nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('prioridade', models.CharField(default='ALTA', max_length=10)),
                ('status', models.CharField(choices=[('ABERTO', 'ABERTO'), ('ATENDIMENTO', 'EM_ATENDIMENTO'), ('ENCERRADO', 'ENCERRADO')], default='ABERTO', max_length=16)),
                ('despachado_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaturas.viatura')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panic.dispositivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
