# Generated by Django 5.2.6 on 2025-11-09 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('processo_mp', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=255)),
                ('documento_mp', models.FileField(upload_to='mp_docs/')),
                ('status', models.CharField(choices=[('PENDENTE_VALIDACAO', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('SUSPENSO', 'Suspenso')], default='PENDENTE_VALIDACAO', max_length=20)),
                ('token_panico', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('observacao_validacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisparoPanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada'), ('FALSO_POSITIVO', 'Falso positivo')], default='ABERTA', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('precisao_m', models.IntegerField(blank=True, null=True)),
                ('origem', models.CharField(default='APP', max_length=20)),
                ('origem_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('origem_user_agent', models.CharField(blank=True, max_length=512)),
                ('midia', models.FileField(blank=True, null=True, upload_to='panico_midia/')),
                ('em_atendimento_em', models.DateTimeField(blank=True, null=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('relato_final', models.TextField(blank=True, null=True)),
                ('assistida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panic.assistida')),
                ('assumido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='panic_dispa_status_fd3781_idx'), models.Index(fields=['assistida'], name='panic_dispa_assisti_323c14_idx'), models.Index(fields=['created_at'], name='panic_dispa_created_370b33_idx')],
            },
        ),
    ]
