# Generated by Django 5.2.6 on 2025-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0002_assistida_disparopanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistida',
            name='token_panico',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
