# Generated by Django 5.2.6 on 2025-11-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panic', '0003_alter_token_panico_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disparopanico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ATENDIMENTO', 'Em atendimento'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada'), ('FALSO_POSITIVO', 'Falso positivo'), ('TESTE', 'Teste')], default='ABERTA', max_length=20),
        ),
    ]
