# Generated by Django 5.2.6 on 2025-10-10 16:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1=Jan ... 12=Dez')),
                ('arquivo', models.ImageField(upload_to=core.models.escala_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
