# Generated by Django 5.2.6 on 2025-10-10 16:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalamensal',
            name='arquivo',
            field=models.FileField(upload_to=core.models.escala_upload_path),
        ),
    ]
