# Generated by Django 5.2.6 on 2025-10-10 18:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audiencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1=Jan ... 12=Dez')),
                ('arquivo', models.FileField(upload_to=core.models.ordem_servico_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ano', '-mes', '-updated_at', '-created_at'],
            },
        ),
    ]
