# Generated by Django 5.2.6 on 2025-10-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ordemservico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantao', models.CharField(choices=[('A', 'Plantão A'), ('B', 'Plantão B'), ('C', 'Plantão C'), ('D', 'Plantão D')], max_length=1)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('LEI', 'Dispensa de Lei'), ('BANCO', 'Banco de Horas'), ('TROCA', 'Troca de Serviço')], max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de aprovação'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('mensagem_recusa', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('recusado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensas_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensas_para_aprovar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'data'), name='uniq_dispensa_por_dia_por_usuario'), models.CheckConstraint(condition=models.Q(('plantao__in', ['A', 'B', 'C', 'D'])), name='disp_plantao_valido')],
            },
        ),
    ]
