# Generated by Django 5.2.6 on 2025-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dispensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensa',
            name='turno',
            field=models.CharField(choices=[('DIURNO', 'Diurno'), ('NOTURNO', 'Noturno')], default='DIURNO', max_length=8),
        ),
    ]
