# Generated by Django 5.2.6 on 2025-10-28 14:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dispensa_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoFiscalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=32, unique=True)),
                ('emissao_em', models.DateTimeField(auto_now_add=True)),
                ('notificado_nome', models.CharField(max_length=200)),
                ('notificado_cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('atividade_ramo', models.CharField(blank=True, max_length=160)),
                ('referente', models.TextField(blank=True)),
                ('prazo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('compareceu_em', models.DateField(blank=True, null=True)),
                ('fiscal_matricula', models.CharField(blank=True, max_length=30)),
                ('recusou_assinar', models.BooleanField(default=False)),
                ('assinatura_notificado', models.ImageField(blank=True, null=True, upload_to=core.models.notificacao_assinatura_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-emissao_em', '-created_at'],
            },
        ),
    ]
