# Generated by Django 5.2.6 on 2025-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificacaofiscalizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaofiscalizacao',
            name='notificado_cpf_cnpj',
        ),
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='notificado_cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='notificado_cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='notificado_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
