# Generated by Django 5.2.6 on 2025-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_notificacaofiscalizacao_notificado_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='validacao_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='validacao_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
