# Generated by Django 5.2.6 on 2025-10-28 19:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificacaofiscalizacao_validacao_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoInfracaoComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=32, unique=True)),
                ('emissao_em', models.DateTimeField(auto_now_add=True)),
                ('notificado_nome', models.CharField(max_length=200)),
                ('notificado_email', models.EmailField(blank=True, max_length=254)),
                ('notificado_cpf', models.CharField(blank=True, max_length=14)),
                ('notificado_cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=40)),
                ('profissao_atividade', models.CharField(blank=True, max_length=160)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=60)),
                ('descricao_infracao', models.TextField(blank=True)),
                ('artigos_infringidos', models.CharField(blank=True, max_length=160)),
                ('lei_numero', models.CharField(blank=True, max_length=80)),
                ('lei_data', models.DateField(blank=True, null=True)),
                ('valor_multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notificacao_entrega', models.CharField(blank=True, choices=[('PES', 'Entregue pessoalmente'), ('POS', 'Via postal')], max_length=3)),
                ('prazo_defesa_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('fiscal_matricula', models.CharField(blank=True, max_length=30)),
                ('recusou_assinar', models.BooleanField(default=False)),
                ('assinatura_notificado', models.ImageField(blank=True, null=True, upload_to=core.models.auto_com_assinatura_upload)),
                ('validacao_token', models.CharField(blank=True, max_length=64)),
                ('validacao_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autos_comercio_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-emissao_em', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoInfracaoSom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=32, unique=True)),
                ('emissao_em', models.DateTimeField(auto_now_add=True)),
                ('notificado_nome', models.CharField(max_length=200)),
                ('notificado_email', models.EmailField(blank=True, max_length=254)),
                ('notificado_cpf', models.CharField(blank=True, max_length=14)),
                ('notificado_cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=160)),
                ('ponto', models.CharField(blank=True, max_length=80)),
                ('valor_medido_db', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('permitido_db', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('DIURNO', 'Diurno (7h–19h)'), ('VESPERTINO', 'Vespertino (19h–22h)'), ('NOTURNO', 'Noturno (22h–7h)')], max_length=10)),
                ('reincidencia', models.CharField(choices=[('0', 'Não'), ('1', '1ª'), ('2', '2ª'), ('3', '3ª'), ('10', '10ª')], default='0', max_length=3)),
                ('base_legal', models.TextField(blank=True)),
                ('classificacao', models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave'), ('GRAVISSIMA', 'Gravíssima')], max_length=12)),
                ('observacoes', models.TextField(blank=True)),
                ('fiscal_matricula', models.CharField(blank=True, max_length=30)),
                ('recusou_assinar', models.BooleanField(default=False)),
                ('assinatura_notificado', models.ImageField(blank=True, null=True, upload_to=core.models.auto_som_assinatura_upload)),
                ('validacao_token', models.CharField(blank=True, max_length=64)),
                ('validacao_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autos_som_fiscal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-emissao_em', '-created_at'],
            },
        ),
    ]
