# Generated by Django 5.2.6 on 2025-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_autoinfracaocomercio_autoinfracaosom'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoinfracaocomercio',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando despacho'), ('DESPACHADO', 'Despachado')], db_index=True, default='AGUARDANDO', max_length=16),
        ),
        migrations.AddField(
            model_name='autoinfracaosom',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando despacho'), ('DESPACHADO', 'Despachado')], db_index=True, default='AGUARDANDO', max_length=16),
        ),
        migrations.AddField(
            model_name='notificacaofiscalizacao',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando despacho'), ('DESPACHADO', 'Despachado')], db_index=True, default='AGUARDANDO', max_length=16),
        ),
    ]
