# Generated by Django 5.2.6 on 2025-10-30 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_autoinfracaocomercio_status_autoinfracaosom_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('SOL', 'Solicitação'), ('JUS', 'Justificativa'), ('SUG', 'Sugestão'), ('CRI', 'Crítica')], max_length=4)),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('PEND_SUP', 'Pendente do Supervisor'), ('PEND_SUB', 'Pendente do Subcomandante'), ('PEND_CMT', 'Pendente do Comandante'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido')], db_index=True, default='PEND_SUP', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios_pendentes', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oficios_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OficioAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criar'), ('DEFERIR', 'Deferir'), ('INDEFERIR', 'Indeferir'), ('DESP_SUB', 'Despachar para SUBCMT'), ('DESP_CMT', 'Despachar para CMT')], max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_acoes', to=settings.AUTH_USER_MODEL)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.oficiointerno')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
