# Generated by Django 5.2.6 on 2025-10-31 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensa',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensa',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispensa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de aprovação'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10),
        ),
    ]
