# Generated by Django 5.2.6 on 2025-10-31 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dispensa_cancelado_em_dispensa_cancelado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispensa',
            name='uniq_dispensa_por_dia_por_usuario',
        ),
        migrations.AddConstraint(
            model_name='dispensa',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDENTE', 'APROVADA', 'RECUSADA'])), fields=('solicitante', 'data'), name='uniq_dispensa_dia_usuario_nao_cancelada'),
        ),
    ]
