# Generated by Django 5.2.6 on 2025-11-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_dispensa_uniq_dispensa_dia_usuario_nao_cancelada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoHorasLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.IntegerField(help_text='Valor em minutos. Positivo adiciona, negativo subtrai.')),
                ('origem', models.CharField(choices=[('MANUAL', 'Ajuste Manual'), ('LIVRO_CECOM', 'Livro CECOM'), ('DISPENSA', 'Dispensa - Banco de Horas')], default='MANUAL', max_length=16)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_horas_lancamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BancoHorasSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_minutos', models.IntegerField(default=0, help_text='Saldo em minutos (positivo=crédito, negativo=débito)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_horas_saldo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Banco de Horas',
                'verbose_name_plural': 'Saldos de Banco de Horas',
            },
        ),
    ]
