# Generated by Django 5.2.6 on 2025-10-22 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARMA', 'Arma'), ('COLETE', 'Colete'), ('TABLET', 'Tablet'), ('VEICULO', 'Veículo'), ('RADIO', 'Rádio'), ('CONE', 'Cone'), ('OUTRO', 'Outro')], max_length=10)),
                ('nome', models.CharField(max_length=150)),
                ('tombamento', models.CharField(blank=True, default='', max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('calibre', models.CharField(blank=True, default='', max_length=20)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bem Patrimonial',
                'verbose_name_plural': 'Bens Patrimoniais',
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['tipo'], name='almoxarifad_tipo_f39cc4_idx'), models.Index(fields=['tombamento'], name='almoxarifad_tombame_1ceb1a_idx'), models.Index(fields=['numero_serie'], name='almoxarifad_numero__57f9a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, default='un', max_length=20)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='almoxarifado.categoriaproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='almoxarifado.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CautelaPermanente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('devolvido_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cautelas_permanentes', to='almoxarifado.bempatrimonial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cautela Permanente',
                'verbose_name_plural': 'Cautelas Permanentes',
                'ordering': ['-atribuido_em'],
                'indexes': [models.Index(fields=['bem', 'usuario', 'atribuido_em'], name='almoxarifad_bem_id_f2d73b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisparoArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disparos', to='almoxarifado.bempatrimonial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disparo de Arma',
                'verbose_name_plural': 'Disparos de Arma',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['bem', 'data'], name='almoxarifad_bem_id_b4650e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA', 'Saída'), ('ENTRADA', 'Entrada')], max_length=7)),
                ('checklist_saida_json', models.TextField(blank=True, default='')),
                ('checklist_entrada_json', models.TextField(blank=True, default='')),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas_agente', to=settings.AUTH_USER_MODEL)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='almoxarifado.bempatrimonial')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas_registrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Cautela',
                'verbose_name_plural': 'Movimentações de Cautela',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['bem', 'criado_em'], name='almoxarifad_bem_id_16a9f2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='almoxarifad_nome_f66915_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo'], name='almoxarifad_ativo_ceb61a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', 'criado_em'], name='almoxarifad_produto_fbc80d_idx'),
        ),
    ]
