# Generated by Django 5.2.6 on 2025-10-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='classe',
            field=models.CharField(choices=[('ARMAMENTO', 'Armamento'), ('MUNICAO', 'Munição')], default='ARMAMENTO', max_length=10),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='grupo',
            field=models.CharField(choices=[('SUPORTE', 'Suporte'), ('FIXO', 'Fixo')], default='SUPORTE', max_length=10),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='subtipo_armamento',
            field=models.CharField(blank=True, choices=[('PISTOLA', 'Pistola'), ('CTT', 'CTT'), ('CAL12', 'Calibre 12'), ('FUZIL', 'Fuzil')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['grupo', 'classe'], name='almoxarifad_grupo_075888_idx'),
        ),
    ]
