# Generated by Django 5.2.6 on 2025-10-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_bempatrimonial_classe_bempatrimonial_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cautelapermanente',
            options={'ordering': ['-atribuido_em'], 'permissions': (('gerir_assignacoes_fixas', 'Pode criar/encerrar termos de responsabilidade (fixo)'), ('verificacao_periodica', 'Pode realizar verificação periódica de armamento fixo')), 'verbose_name': 'Cautela Permanente', 'verbose_name_plural': 'Cautelas Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaocautela',
            options={'ordering': ['-criado_em'], 'permissions': (('aprovar_cautela', 'Pode aprovar solicitações de cautela'), ('entregar_cautela', 'Pode entregar/abrir cautela'), ('devolver_cautela', 'Pode receber/devolver e encerrar cautela'), ('desbloquear_excecao', 'Pode desbloquear exceções (atrasos/fora de horário)'), ('ver_auditoria', 'Pode visualizar trilhas de auditoria relacionadas')), 'verbose_name': 'Movimentação de Cautela', 'verbose_name_plural': 'Movimentações de Cautela'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-criado_em'], 'permissions': (('movimentar_estoque', 'Pode movimentar estoque de munição/itens'), ('ver_livro_municao', 'Pode visualizar o livro/relatórios de munição')), 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
    ]
