# Generated by Django 5.2.6 on 2025-10-22 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_alter_cautelapermanente_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('SUPORTE', 'Suporte'), ('FIXO', 'Fixo')], max_length=10)),
                ('data_hora_retirada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_prevista_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_hora_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=10)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('rev', models.PositiveIntegerField(default=1, help_text='Versão para controle otimista')),
                ('almoxarife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautelas_almoxarife', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautelas_supervisor', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cautela',
                'verbose_name_plural': 'Cautelas',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CautelaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('item_tipo', models.CharField(choices=[('ARMAMENTO', 'Armamento'), ('MUNICAO', 'Munição'), ('ACESSORIO', 'Acessório')], max_length=12)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('estado_saida', models.CharField(blank=True, default='', max_length=120)),
                ('estado_retorno', models.CharField(blank=True, default='', max_length=120)),
                ('cautela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='almoxarifado.cautela')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Item de Cautela',
                'verbose_name_plural': 'Itens de Cautela',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('BAIXA', 'Baixa')], max_length=12)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255)),
                ('impacta_disponibilidade', models.BooleanField(default=True)),
                ('armamento', models.ForeignKey(limit_choices_to={'classe': 'ARMAMENTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='almoxarifado.bempatrimonial')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ('-data_inicio', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('calibre', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('TREINO', 'Treino'), ('OPERACIONAL', 'Operacional')], default='OPERACIONAL', max_length=12)),
                ('lote', models.CharField(db_index=True, max_length=60)),
                ('validade', models.DateField(blank=True, null=True)),
                ('unidade_medida', models.CharField(default='un', max_length=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'Munição',
                'verbose_name_plural': 'Munições',
                'ordering': ['calibre', 'lote'],
                'indexes': [models.Index(fields=['calibre', 'lote'], name='almoxarifad_calibre_998a11_idx'), models.Index(fields=['status'], name='almoxarifad_status_e78de1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MunicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('local', models.CharField(db_index=True, default='ALMOXARIFADO', max_length=80)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('quantidade_reservada', models.PositiveIntegerField(default=0)),
                ('municao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='almoxarifado.municao')),
            ],
            options={
                'verbose_name': 'Estoque de Munição',
                'verbose_name_plural': 'Estoques de Munição',
            },
        ),
        migrations.CreateModel(
            name='AssignacaoFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('termo_pdf', models.FileField(blank=True, null=True, upload_to='termos_fixo/')),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=10)),
                ('armamento', models.ForeignKey(limit_choices_to={'classe': 'ARMAMENTO'}, on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.bempatrimonial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignação Fixa',
                'verbose_name_plural': 'Assignações Fixas',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['usuario', 'status'], name='almoxarifad_usuario_815a3e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['status'], name='almoxarifad_status_4c569d_idx'),
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['tipo', 'status'], name='almoxarifad_tipo_86a0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cautela',
            index=models.Index(fields=['usuario', 'status'], name='almoxarifad_usuario_2a2821_idx'),
        ),
        migrations.AddIndex(
            model_name='cautelaitem',
            index=models.Index(fields=['cautela'], name='almoxarifad_cautela_687ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['armamento', 'data_inicio'], name='almoxarifad_armamen_d586ea_idx'),
        ),
        migrations.AddIndex(
            model_name='municaoestoque',
            index=models.Index(fields=['local'], name='almoxarifad_local_9a22b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='municaoestoque',
            unique_together={('municao', 'local')},
        ),
    ]
