# Generated by Django 5.2.6 on 2025-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_cautela_cautelaitem_manutencao_municao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cautela',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente Aprovação'), ('APROVADA', 'Aprovada'), ('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=10),
        ),
    ]
