# Generated by Django 5.2.6 on 2025-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_cautela_aprovada_em_alter_cautela_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
