# Generated by Django 5.2.6 on 2025-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_bempatrimonial_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='subtipo_armamento',
            field=models.CharField(blank=True, choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('CTT', 'CTT'), ('CAL12', 'Calibre 12'), ('FUZIL', 'Fuzil')], default='', max_length=10),
        ),
    ]
