# Generated by Django 5.2.6 on 2025-10-25 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0007_alter_bempatrimonial_subtipo_armamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bens_proprios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['dono'], name='almoxarifad_dono_id_4cbf00_idx'),
        ),
    ]
