# Generated by Django 5.2.6 on 2025-10-25 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_bempatrimonial_dono_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddIndex(
            model_name='bempatrimonial',
            index=models.Index(fields=['lote'], name='almoxarifad_lote_e10beb_idx'),
        ),
    ]
