# Generated by Django 5.2.6 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_bempatrimonial_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='subtipo_armamento',
            field=models.CharField(blank=True, choices=[('PISTOLA', 'Pistola'), ('REVOLVER', 'Revólver'), ('CTT', 'Carabina'), ('CAL12', 'Espingarda'), ('FUZIL', 'Fuzil')], default='', max_length=10),
        ),
    ]
