# Generated by Django 5.2 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_alter_bempatrimonial_subtipo_armamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='classe',
            field=models.CharField(
                choices=[
                    ('ARMAMENTO', 'Armamento'),
                    ('MUNICAO', 'Munição'),
                    ('PLACA_BALISTICA', 'Placa Balística'),
                ],
                default='ARMAMENTO',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='placa_marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='placa_modelo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='placa_numero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='placa_nivel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='placa_tamanho',
            field=models.CharField(
                blank=True,
                choices=[
                    ('PP', 'PP'),
                    ('P', 'P'),
                    ('M', 'M'),
                    ('G', 'G'),
                    ('GG', 'GG'),
                ],
                default='',
                max_length=10,
            ),
        ),
    ]
