# Generated by Django 5.2.5 on 2025-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_placa_balistica_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='classe',
            field=models.CharField(choices=[('ARMAMENTO', 'Armamento'), ('MUNICAO', 'Munição'), ('PLACA_BALISTICA', 'Placa Balística')], default='ARMAMENTO', max_length=20),
        ),
    ]
