# Generated by Django 5.2.6 on 2025-09-18 14:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0001_initial'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('nome_solicitante', models.CharField(blank=True, max_length=100, verbose_name='Nome do solicitante')),
                ('telefone_solicitante', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('descricao', models.TextField(verbose_name='Descrição da ocorrência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('despachado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Despachado em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('despachado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Despachado por')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaturas.viatura', verbose_name='Viatura')),
            ],
            options={
                'verbose_name': 'Despacho de Ocorrência',
                'verbose_name_plural': 'Despachos de Ocorrências',
                'ordering': ['-despachado_em'],
            },
        ),
    ]
