# Generated by Django 5.2.6 on 2025-09-18 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0002_despachoocorrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despachoocorrencia',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AddField(
            model_name='despachoocorrencia',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em'),
        ),
        migrations.AddField(
            model_name='despachoocorrencia',
            name='notificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notificado em'),
        ),
        migrations.AddField(
            model_name='despachoocorrencia',
            name='observacoes_encarregado',
            field=models.TextField(blank=True, verbose_name='Observações do encarregado'),
        ),
        migrations.AddField(
            model_name='despachoocorrencia',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido em'),
        ),
        migrations.AddField(
            model_name='despachoocorrencia',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_despachos', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AlterField(
            model_name='despachoocorrencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
