# Generated by Django 5.2.6 on 2025-10-06 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0003_despachoocorrencia_arquivado_and_more'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaocecom',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='viaturas.viatura'),
        ),
        migrations.AlterField(
            model_name='plantaocecom',
            name='iniciado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantoes_iniciados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='plantaocecom',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('viatura',), name='cecom_viatura_unica_plantao_ativo'),
        ),
    ]
