# Generated by Django 5.2.6 on 2025-10-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0004_plantaocecom_viatura_alter_plantaocecom_iniciado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, choices=[('ENC', 'Encarregado'), ('MOT', 'Motorista'), ('AUX1', 'Auxiliar 1'), ('AUX2', 'Auxiliar 2')], default='', max_length=5)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='cecom.plantaocecom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_participados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('plantao', 'usuario')},
            },
        ),
    ]
