# Generated by Django 5.2.6 on 2025-10-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0005_plantaoparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaoparticipante',
            name='saida_em',
            field=models.DateTimeField(blank=True, help_text='Momento em que o participante saiu do plantão (se aplicável).', null=True),
        ),
    ]
