# Generated by Django 5.2.6 on 2025-10-06 21:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0006_plantaoparticipante_saida_em'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroPlantaoCecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_plantao', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('dispensados', models.TextField(blank=True)),
                ('atraso_servico', models.TextField(blank=True)),
                ('banco_horas', models.TextField(blank=True)),
                ('hora_extra', models.TextField(blank=True)),
                ('ocorrencias_nao_atendidas', models.TextField(blank=True)),
                ('ocorrencias_do_plantao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aits_recebidas', models.PositiveIntegerField(default=0)),
                ('chk_radio', models.BooleanField(default=False)),
                ('chk_computador', models.BooleanField(default=False)),
                ('chk_cameras', models.BooleanField(default=False)),
                ('chk_celulares', models.BooleanField(default=False)),
                ('chk_carregadores', models.BooleanField(default=False)),
                ('chk_telefones', models.BooleanField(default=False)),
                ('chk_livros', models.BooleanField(default=False)),
                ('chk_monitor', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cga_do_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cga_dia_plantoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivroPlantaoCecomPostoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREFEITURA', 'Prefeitura'), ('HOSPITAL', 'Hospital'), ('SUBSEDE_VERAVA', 'Subsede Verava'), ('OUTROS', 'Outros')], max_length=30)),
                ('descricao_outros', models.CharField(blank=True, max_length=120)),
                ('gcm1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gcm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos_fixos', to='cecom.livroplantaocecom')),
            ],
        ),
        migrations.CreateModel(
            name='LivroPlantaoCecomViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrante1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integrante2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integrante3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('integrante4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaturas', to='cecom.livroplantaocecom')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viaturas.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='PlantaoCecomPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aux_cecom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantoes_cecom_auxiliares', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_cecom_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-inicio',),
            },
        ),
        migrations.AddField(
            model_name='livroplantaocecom',
            name='plantao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='cecom.plantaocecomprincipal'),
        ),
        migrations.AddConstraint(
            model_name='plantaocecomprincipal',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('usuario',), name='cecom_unique_principal_ativo'),
        ),
    ]
