# Generated by Django 5.2.6 on 2025-10-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0007_livroplantaocecom_livroplantaocecompostofixo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroPlantaoCecomRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='cecom_livros/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe_plantao', models.CharField(blank=True, max_length=1)),
                ('cga_nome', models.CharField(blank=True, max_length=120)),
                ('cga_matricula', models.CharField(blank=True, max_length=30)),
                ('plantao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_pdf', to='cecom.plantaocecomprincipal')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
