# Generated by Django 5.2.6 on 2025-10-13 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0008_livroplantaocecomrelatorio'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroplantaocecompostofixo',
            name='tipo',
            field=models.CharField(choices=[('PREFEITURA', 'Prefeitura'), ('HOSPITAL', 'Hospital'), ('SUBSEDE_VERAVA', 'Subsede Verava'), ('ADM', 'ADM'), ('DELEGACIA', 'Delegacia'), ('RECEPCAO', 'Recepção'), ('CECOM', 'CECOM'), ('AUX_CECOM', 'AUX CECOM'), ('OUTROS', 'Outros')], max_length=30),
        ),
        migrations.CreateModel(
            name='ViaturaLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('precisao_m', models.FloatField(blank=True, null=True)),
                ('velocidade_kmh', models.FloatField(blank=True, null=True)),
                ('direcao_graus', models.FloatField(blank=True, help_text='0-360, 0=Norte', null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem_plantao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cecom.plantaocecom')),
                ('origem_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Localização de Viatura',
                'verbose_name_plural': 'Localizações de Viaturas',
                'indexes': [models.Index(fields=['atualizado_em'], name='cecom_viatu_atualiz_b0ffc4_idx')],
            },
        ),
    ]
