# Generated by Django 5.2.6 on 2025-10-14 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0009_alter_livroplantaocecompostofixo_tipo_and_more'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaturaLocalizacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('capturado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('precisao_m', models.FloatField(blank=True, null=True)),
                ('origem_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_pontos', to='cecom.plantaocecom')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_pontos', to='viaturas.viatura')),
            ],
            options={
                'ordering': ['-capturado_em'],
                'indexes': [models.Index(fields=['viatura', 'capturado_em'], name='cecom_viatu_viatura_68bebd_idx')],
            },
        ),
    ]
