# Generated by Django 5.2.6 on 2025-10-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0010_viaturalocalizacaoponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaocecom',
            name='relatorio_rascunho',
            field=models.TextField(blank=True, default=''),
        ),
    ]
