# Generated by Django 5.2.6 on 2025-10-21 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0011_plantaocecom_relatorio_rascunho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroPlantaoCecomPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DISP', 'Dispensados'), ('ATRASO', 'Atraso ao Serviço'), ('BANCO', 'Banco de Horas'), ('HORA_EXTRA', 'Hora Extra')], max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='cecom.livroplantaocecom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tipo', 'id'),
                'unique_together': {('livro', 'tipo', 'usuario')},
            },
        ),
    ]
