# Generated by Django 5.2.6 on 2025-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0012_livroplantaocecompessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroplantaocecompessoa',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livroplantaocecompessoa',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livroplantaocecompessoa',
            name='total_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
