# Generated by Django 5.2.6 on 2025-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0013_livroplantaocecompessoa_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroplantaocecomrelatorio',
            name='verificacao_token',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
