# Generated by Django 5.2.6 on 2025-10-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecom', '0014_livroplantaocecomrelatorio_verificacao_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaocecom',
            name='verificacao_token',
            field=models.CharField(blank=True, default=None, null=True, max_length=64, unique=True),
        ),
    ]
