# Generated by Django 5.2.6 on 2025-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NaturezaOcorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(db_index=True, max_length=20)),
                ("grupo_nome", models.CharField(max_length=120)),
                ("codigo", models.CharField(db_index=True, max_length=10, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Natureza de ocorrência",
                "verbose_name_plural": "Naturezas de ocorrência",
                "ordering": ("grupo", "codigo"),
            },
        ),
    ]
