# Generated by Django 5.2.6 on 2025-09-18 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAssinavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PLANTAO', 'Relatório de Plantão'), ('BOGCMI', 'BOGCMI')], db_index=True, max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/origem/')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='documentos/assinados/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Assinatura Comando'), ('ASSINADO', 'Despachado / Arquivado')], db_index=True, default='PENDENTE', max_length=20)),
                ('encarregado_assinou', models.BooleanField(default=False)),
                ('comando_assinou', models.BooleanField(default=False)),
                ('comando_assinou_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('comando_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_assinados', to=settings.AUTH_USER_MODEL)),
                ('usuario_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
