# Generated by Django 5.2.6 on 2025-10-12 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_documentoassinavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoassinavel',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente Assinatura Comando'), ('ASSINADO', 'Despachado / Arquivado'), ('PENDENTE_ADM', 'Pendente Assinatura do Administrativo'), ('ASSINADO_ADM', 'Despacho / Assinatura do Administrativo')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoassinavel',
            name='tipo',
            field=models.CharField(choices=[('PLANTAO', 'Relatório de Plantão'), ('BOGCMI', 'BOGCMI'), ('LIVRO_CECOM', 'Livro CECOM')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('action', models.CharField(blank=True, help_text='Descrição resumida da ação (opcional)', max_length=120)),
                ('querystring', models.CharField(blank=True, max_length=1000)),
                ('body', models.TextField(blank=True, help_text='Corpo da requisição (truncado)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='common_audi_created_5f768f_idx'), models.Index(fields=['method'], name='common_audi_method_f3d11a_idx'), models.Index(fields=['path'], name='common_audi_path_d3e5ea_idx')],
            },
        ),
    ]
