# Generated by Django 5.2.6 on 2025-10-22 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pushdevice'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('event', models.CharField(choices=[('SOLICITAR', 'Solicitar'), ('APROVAR', 'Aprovar'), ('ENTREGAR', 'Entregar'), ('DEVOLVER', 'Devolver'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('before', models.TextField(blank=True, help_text='Snapshot anterior em JSON')),
                ('after', models.TextField(blank=True, help_text='Snapshot posterior em JSON')),
                ('hash_prev', models.CharField(blank=True, db_index=True, max_length=64)),
                ('hash_current', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='common_push_user_id_9e1813_idx',
            old_name='common_push_user_plat_idx',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='common_audi_content_7e5bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['event', 'created_at'], name='common_audi_event_a7a56a_idx'),
        ),
    ]
