# Generated by Django 5.2.6 on 2025-11-14 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_pushdevice_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('event', models.CharField(db_index=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Representação curta do alvo', max_length=255)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('extra', models.TextField(blank=True, help_text='JSON textual opcional com dados extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['created_at'], name='common_simp_created_acadb1_idx'), models.Index(fields=['app_label', 'event', 'created_at'], name='common_simp_app_lab_deffda_idx'), models.Index(fields=['user', 'created_at'], name='common_simp_user_id_4bbc3c_idx')],
            },
        ),
    ]
