from django.urls import path, include
from . import views
from . import config_views

app_name = 'core'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('notificacoes/', views.notificacoes_usuario, name='notificacoes'),
    path('notificacoes/confirmar/<int:pk>/', views.confirmar_notificacao_usuario, name='confirmar_notificacao'),
    path('despacho/<int:despacho_id>/responder/', views.responder_despacho, name='responder_despacho'),
    path('notificacoes/push-teste/', views.push_teste_usuario, name='push_teste_usuario'),
    path('administracao/banco-de-horas/', views.banco_de_horas, name='banco_de_horas'),
    path('administracao/banco-de-horas/ajustar/', views.banco_de_horas_ajustar, name='banco_de_horas_ajustar'),
    path('administracao/banco-de-horas/<int:user_id>/lancamentos/', views.banco_de_horas_lancamentos, name='banco_de_horas_lancamentos'),
    path('administracao/escala-mensal/', views.escala_mensal, name='escala_mensal'),
    path('administracao/escala-mensal/upload/', views.escala_mensal_upload, name='escala_mensal_upload'),
    path('administracao/escala-mensal/<int:ano>/<int:mes>/remover/', views.escala_mensal_remover, name='escala_mensal_remover'),
    path('administracao/ordem-de-servico/', views.ordem_servico, name='ordem_servico'),
        path('administracao/ordem-servico/upload/', views.ordem_servico_upload, name='ordem_servico_upload'),
        path('administracao/ordem-servico/<int:os_id>/remover/', views.ordem_servico_remover, name='ordem_servico_remover'),
    path('administracao/oficio-interno/', views.oficio_interno, name='oficio_interno'),
    path('administracao/oficio-interno/novo/', views.oficio_interno_novo, name='oficio_interno_novo'),
    path('administracao/oficio-interno/<int:pk>/', views.oficio_interno_ver, name='oficio_interno_ver'),
    path('administracao/oficio-interno/<int:pk>/excluir/', views.oficio_interno_excluir, name='oficio_interno_excluir'),
    path('administracao/oficio-interno/<int:pk>/acao/', views.oficio_interno_acao, name='oficio_interno_acao'),
    path('administracao/audiencias/', views.audiencias, name='audiencias'),
    path('administracao/audiencias/upload/', views.audiencias_upload, name='audiencias_upload'),
    path('administracao/audiencias/remover/', views.audiencias_remover, name='audiencias_remover'),
    path('administracao/log-sistema/', views.log_sistema, name='log_sistema'),
    path('administracao/log-simplificado/', views.log_simplificado, name='log_simplificado'),
    path('administracao/almoxarifado/', views.almoxarifado, name='almoxarifado'),
    path('administracao/dispensas/', views.dispensas, name='dispensas'),
    path('administracao/dispensas/solicitar/', views.dispensas_solicitar, name='dispensas_solicitar'),
    path('administracao/dispensas/<int:dispensa_id>/aprovar/', views.dispensas_aprovar, name='dispensas_aprovar'),
    path('administracao/dispensas/<int:dispensa_id>/cancelar/', views.dispensas_cancelar, name='dispensas_cancelar'),
    path('administracao/dispensas/<int:dispensa_id>/excluir/', views.dispensas_excluir, name='dispensas_excluir'),
    path('administracao/estatisticas/', views.estatisticas, name='estatisticas'),
    path('administracao/estatisticas/bo/', views.estatisticas_bo, name='estatisticas_bo'),
    path('administracao/estatisticas/bo/mapa/', views.estatisticas_bo_mapa, name='estatisticas_bo_mapa'),
    path('administracao/estatisticas/bo/mapa/data.json', views.estatisticas_bo_mapa_data, name='estatisticas_bo_mapa_data'),
    path('administracao/estatisticas/bo/codigo/', views.estatisticas_bo_codigo, name='estatisticas_bo_codigo'),
    path('administracao/estatisticas/bo/usuario/', views.estatisticas_bo_usuario, name='estatisticas_bo_usuario'),
    path('administracao/estatisticas/bo/usuario/graficos/', views.estatisticas_bo_usuario_graficos, name='estatisticas_bo_usuario_graficos'),
        path('administracao/estatisticas/bo/usuario/graficos/pdf/', views.estatisticas_bo_usuario_graficos_pdf, name='estatisticas_bo_usuario_graficos_pdf'),
    path('administracao/estatisticas/ait/', views.estatisticas_ait, name='estatisticas_ait'),
    path('administracao/estatisticas/ait/graficos/', views.estatisticas_ait_graficos, name='estatisticas_ait_graficos'),
    path('administracao/estatisticas/abordados/', views.estatisticas_abordados, name='estatisticas_abordados'),
    path('administracao/estatisticas/abordados/graficos/', views.estatisticas_abordados_graficos, name='estatisticas_abordados_graficos'),
    path('administracao/estatisticas/policiamentos/', views.estatisticas_policiamentos, name='estatisticas_policiamentos'),
    path('administracao/estatisticas/policiamentos/graficos/', views.estatisticas_policiamentos_graficos, name='estatisticas_policiamentos_graficos'),
    path('administracao/estatisticas/cecom/', views.estatisticas_cecom, name='estatisticas_cecom'),
    path('administracao/estatisticas/cecom/graficos/', views.estatisticas_cecom_graficos, name='estatisticas_cecom_graficos'),
    path('administracao/estatisticas/remocoes/', views.estatisticas_remocoes, name='estatisticas_remocoes'),
    path('administracao/estatisticas/remocoes/graficos/', views.estatisticas_remocoes_graficos, name='estatisticas_remocoes_graficos'),
    path(
        'administracao/almoxarifado/',
        include((
            'almoxarifado.urls',
            'almoxarifado'
        ), namespace='almoxarifado')
    ),
        # Fiscalização
        path('fiscalizacao/notificacao/', views.fiscalizacao_notificacao, name='fisc_notificacao'),
        path('fiscalizacao/notificacao/novo/', views.fiscalizacao_notificacao_novo, name='fisc_notificacao_novo'),
        path('fiscalizacao/notificacao/<int:pk>/editar/', views.fiscalizacao_notificacao_editar, name='fisc_notificacao_editar'),
        path('fiscalizacao/notificacao/<int:pk>/excluir/', views.fiscalizacao_notificacao_excluir, name='fisc_notificacao_excluir'),
    path('fiscalizacao/notificacao/<int:pk>/documento/', views.fisc_notificacao_documento, name='fisc_notificacao_documento'),
    path('fiscalizacao/notificacao/<int:pk>/baixar-pdf/', views.fisc_notificacao_baixar_pdf, name='fisc_notificacao_baixar_pdf'),
    path('fiscalizacao/notificacao/<int:pk>/verificar/<str:token>/', views.fisc_notificacao_validar, name='fisc_notificacao_validar'),
    path('fiscalizacao/auto-comercio/', views.fiscalizacao_auto_comercio, name='fisc_auto_comercio'),
    path('fiscalizacao/auto-comercio/novo/', views.fiscalizacao_auto_comercio_novo, name='fisc_auto_comercio_novo'),
    path('fiscalizacao/auto-comercio/<int:pk>/editar/', views.fiscalizacao_auto_comercio_editar, name='fisc_auto_comercio_editar'),
    path('fiscalizacao/auto-comercio/<int:pk>/excluir/', views.fiscalizacao_auto_comercio_excluir, name='fisc_auto_comercio_excluir'),
    path('fiscalizacao/auto-comercio/<int:pk>/documento/', views.fisc_auto_comercio_documento, name='fisc_auto_comercio_documento'),
    path('fiscalizacao/auto-comercio/<int:pk>/baixar-pdf/', views.fisc_auto_comercio_baixar_pdf, name='fisc_auto_comercio_baixar_pdf'),
    path('fiscalizacao/auto-comercio/<int:pk>/verificar/<str:token>/', views.fisc_auto_comercio_validar, name='fisc_auto_comercio_validar'),

    path('fiscalizacao/auto-som/', views.fiscalizacao_auto_som, name='fisc_auto_som'),
    path('fiscalizacao/auto-som/novo/', views.fiscalizacao_auto_som_novo, name='fisc_auto_som_novo'),
    path('fiscalizacao/auto-som/<int:pk>/editar/', views.fiscalizacao_auto_som_editar, name='fisc_auto_som_editar'),
    path('fiscalizacao/auto-som/<int:pk>/excluir/', views.fiscalizacao_auto_som_excluir, name='fisc_auto_som_excluir'),
    path('fiscalizacao/auto-som/<int:pk>/documento/', views.fisc_auto_som_documento, name='fisc_auto_som_documento'),
    path('fiscalizacao/auto-som/<int:pk>/baixar-pdf/', views.fisc_auto_som_baixar_pdf, name='fisc_auto_som_baixar_pdf'),
    path('fiscalizacao/auto-som/<int:pk>/verificar/<str:token>/', views.fisc_auto_som_validar, name='fisc_auto_som_validar'),
    # Alteração de status (AJAX)
    path('fiscalizacao/<str:tipo>/<int:pk>/status/', views.fiscalizacao_alterar_status, name='fiscalizacao_alterar_status'),
    # Configurações
    path('administracao/configuracoes/', config_views.config_dashboard, name='config_dashboard'),
    path('administracao/configuracoes/usuarios/', config_views.usuarios_list, name='config_usuarios'),
    path('administracao/configuracoes/usuarios/novo/', config_views.usuario_new, name='config_usuario_novo'),
    path('administracao/configuracoes/usuarios/<int:user_id>/editar/', config_views.usuario_edit, name='config_usuario_editar'),
    path('administracao/configuracoes/perfis/', config_views.perfis_list, name='config_perfis'),
    path('administracao/configuracoes/perfis/novo/', config_views.perfil_new, name='config_perfil_novo'),
    path('administracao/configuracoes/perfis/<int:perfil_id>/editar/', config_views.perfil_edit, name='config_perfil_editar'),
]
