# Generated by Django 5.2.6 on 2025-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viaturas", "0002_seed_viaturas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viatura",
            options={
                "ordering": ("prefixo",),
                "verbose_name": "Viatura",
                "verbose_name_plural": "Viaturas",
            },
        ),
        migrations.RenameField(
            model_name="viatura",
            old_name="updated_at",
            new_name="atualizado_em",
        ),
        migrations.RenameField(
            model_name="viatura",
            old_name="created_at",
            new_name="criado_em",
        ),
        migrations.RemoveField(
            model_name="viatura",
            name="modelo",
        ),
        migrations.AddField(
            model_name="viatura",
            name="km_atual",
            field=models.PositiveIntegerField(default=0, verbose_name="KM atual"),
        ),
        migrations.AddField(
            model_name="viatura",
            name="km_prox_revisao",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Próxima revisão (KM)"
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="km_prox_troca_oleo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Próxima troca de óleo (KM)"
            ),
        ),
        migrations.AddField(
            model_name="viatura",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="viatura",
            name="status",
            field=models.CharField(
                choices=[
                    ("FUNC", "Em funcionamento"),
                    ("MANU", "Em manutenção"),
                    ("BAIX", "Baixada (sem previsão)"),
                ],
                db_index=True,
                default="FUNC",
                max_length=4,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativa"),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="placa",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Placa"
            ),
        ),
        migrations.AlterField(
            model_name="viatura",
            name="prefixo",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="Prefixo"
            ),
        ),
    ]
