# Generated by Django 5.2.6 on 2025-10-16 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0003_alter_viatura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaturaAvariaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels_json', models.TextField(blank=True, default='[]')),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('viatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avarias_estado', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Estado de Avarias da Viatura',
                'verbose_name_plural': 'Estados de Avarias das Viaturas',
            },
        ),
    ]
