# Generated by Django 5.2.6 on 2025-10-21 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0004_viaturaavariaestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvariaResolvidaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_json', models.TextField(blank=True, default='[]')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_resolvidas_logs', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Resolução de Avaria',
                'verbose_name_plural': 'Resoluções de Avarias',
                'ordering': ('-criado_em',),
            },
        ),
    ]
