# Generated by Django 5.2.6 on 2025-09-15 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taloes", "0001_initial"),
        ("viaturas", "0003_alter_viatura_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigoocorrencia",
            options={
                "ordering": ("sigla",),
                "verbose_name": "Código de ocorrência",
                "verbose_name_plural": "Códigos de ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="grupoocorrencia",
            options={
                "ordering": ("codigo",),
                "verbose_name": "Grupo de ocorrência",
                "verbose_name_plural": "Grupos de ocorrência",
            },
        ),
        migrations.RemoveField(
            model_name="talao",
            name="equipe_texto",
        ),
        migrations.RemoveField(
            model_name="talao",
            name="local_bairro",
        ),
        migrations.RemoveField(
            model_name="talao",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="talao",
            name="relatorio",
        ),
        migrations.AddField(
            model_name="talao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="local",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="talao",
            name="membros",
            field=models.ManyToManyField(
                blank=True, related_name="taloes_membro", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="codigos",
                to="taloes.grupoocorrencia",
            ),
        ),
        migrations.AlterField(
            model_name="grupoocorrencia",
            name="codigo",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="talao",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taloes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="encerrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talao",
            name="iniciado_em",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="talao",
            name="km_inicial",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="talao",
            name="status",
            field=models.CharField(
                choices=[("ABERTO", "Aberto"), ("FECHADO", "Finalizado")],
                db_index=True,
                default="ABERTO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="viatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taloes",
                to="viaturas.viatura",
            ),
        ),
    ]
