# Generated by Django 5.2.6 on 2025-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taloes", "0002_alter_codigoocorrencia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talao",
            options={"ordering": ("-iniciado_em",)},
        ),
        migrations.AlterField(
            model_name="talao",
            name="encerrado_em",
            field=models.DateTimeField(blank=True, db_column="fim", null=True),
        ),
        migrations.AlterField(
            model_name="talao",
            name="iniciado_em",
            field=models.DateTimeField(
                auto_now_add=True, db_column="inicio", db_index=True
            ),
        ),
    ]
