# Generated by Django 5.2.6 on 2025-09-16 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taloes", "0003_alter_talao_options_alter_talao_encerrado_em_and_more"),
        ("viaturas", "0003_alter_viatura_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigoocorrencia",
            options={
                "ordering": ["sigla"],
                "verbose_name": "Código de ocorrência",
                "verbose_name_plural": "Códigos de ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="grupoocorrencia",
            options={
                "ordering": ["nome"],
                "verbose_name": "Grupo de ocorrência",
                "verbose_name_plural": "Grupos de ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="talao",
            options={
                "ordering": ["-iniciado_em"],
                "verbose_name": "Talão",
                "verbose_name_plural": "Talões",
            },
        ),
        migrations.RemoveField(
            model_name="grupoocorrencia",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="grupoocorrencia",
            name="titulo",
        ),
        migrations.RemoveField(
            model_name="talao",
            name="local",
        ),
        migrations.RemoveField(
            model_name="talao",
            name="membros",
        ),
        migrations.AddField(
            model_name="grupoocorrencia",
            name="descricao",
            field=models.TextField(blank=True, default="", verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="grupoocorrencia",
            name="nome",
            field=models.CharField(default="", max_length=80, verbose_name="Nome"),
        ),
        migrations.AddField(
            model_name="talao",
            name="equipe_texto",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Equipe (snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="local_bairro",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bairro/Localidade"
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="local_logradouro",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Logradouro/Referência",
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="descricao",
            field=models.CharField(
                default="", max_length=200, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codigos",
                to="taloes.grupoocorrencia",
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="sigla",
            field=models.CharField(
                db_index=True, default="", max_length=20, verbose_name="Sigla"
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="encerrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="talao",
            name="iniciado_em",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="km_final",
            field=models.IntegerField(blank=True, null=True, verbose_name="KM final"),
        ),
        migrations.AlterField(
            model_name="talao",
            name="km_inicial",
            field=models.IntegerField(blank=True, default=0, verbose_name="KM inicial"),
        ),
        migrations.AlterField(
            model_name="talao",
            name="status",
            field=models.CharField(
                choices=[("ABERTO", "Aberto"), ("FECHADO", "Fechado")],
                db_index=True,
                default="ABERTO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="viatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes",
                to="viaturas.viatura",
            ),
        ),
    ]
