# Generated by Django 5.2.6 on 2025-09-16 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taloes", "0004_alter_codigoocorrencia_options_and_more"),
        ("viaturas", "0003_alter_viatura_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigoocorrencia",
            options={
                "ordering": ["sigla"],
                "verbose_name": "Código de Ocorrência",
                "verbose_name_plural": "Códigos de Ocorrência",
            },
        ),
        migrations.AlterModelOptions(
            name="grupoocorrencia",
            options={
                "ordering": ["nome"],
                "verbose_name": "Grupo de Ocorrência",
                "verbose_name_plural": "Grupos de Ocorrência",
            },
        ),
        migrations.RemoveField(
            model_name="talao",
            name="local_logradouro",
        ),
        migrations.AddField(
            model_name="talao",
            name="auxiliar1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_auxiliar1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auxiliar 1",
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="auxiliar2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_auxiliar2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auxiliar 2",
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="encarregado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_encarregado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Encarregado",
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="local_rua",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Rua/Logradouro"
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="motorista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_motorista",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Motorista",
            ),
        ),
        migrations.AddField(
            model_name="talao",
            name="plantao",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Plantão"
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="descricao",
            field=models.CharField(
                default="", max_length=255, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="codigoocorrencia",
            name="sigla",
            field=models.CharField(default="", max_length=30, verbose_name="Sigla"),
        ),
        migrations.AlterField(
            model_name="grupoocorrencia",
            name="descricao",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="grupoocorrencia",
            name="nome",
            field=models.CharField(
                default="", max_length=100, verbose_name="Nome do grupo"
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="codigo_ocorrencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes",
                to="taloes.codigoocorrencia",
                verbose_name="Código de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="encerrado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Encerrado em"
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="equipe_texto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Texto consolidado da equipe (encarregado, motorista, auxiliares).",
                max_length=255,
                verbose_name="Equipe (texto)",
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="iniciado_em",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Iniciado em",
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="km_inicial",
            field=models.IntegerField(blank=True, null=True, verbose_name="KM inicial"),
        ),
        migrations.AlterField(
            model_name="talao",
            name="local_bairro",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="status",
            field=models.CharField(
                choices=[("ABERTO", "ABERTO"), ("FECHADO", "FECHADO")],
                default="ABERTO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="talao",
            name="viatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taloes",
                to="viaturas.viatura",
                verbose_name="Viatura",
            ),
        ),
        migrations.AddIndex(
            model_name="codigoocorrencia",
            index=models.Index(fields=["sigla"], name="taloes_codi_sigla_ea5292_idx"),
        ),
        migrations.AddIndex(
            model_name="codigoocorrencia",
            index=models.Index(
                fields=["descricao"], name="taloes_codi_descric_d9a3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talao",
            index=models.Index(fields=["status"], name="taloes_tala_status_f1dd68_idx"),
        ),
        migrations.AddIndex(
            model_name="talao",
            index=models.Index(
                fields=["iniciado_em"], name="taloes_tala_iniciad_464b40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talao",
            index=models.Index(
                fields=["viatura"], name="taloes_tala_viatura_d74359_idx"
            ),
        ),
    ]
