# Generated by Django 5.2.6 on 2025-09-17 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taloes", "0005_alter_codigoocorrencia_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abordado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PESSOA", "Pessoa"), ("VEICULO", "Veículo")],
                        default="PESSOA",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Nome"
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="RG/CPF"
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Placa"
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Modelo"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Cor"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "talao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abordados",
                        to="taloes.talao",
                        verbose_name="Talão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abordado",
                "verbose_name_plural": "Abordados",
                "ordering": ["criado_em"],
            },
        ),
    ]
