# Generated by Django 5.2.6 on 2025-10-06 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0006_abordado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('plantao_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('radio_comunicador', models.BooleanField(default=False)),
                ('sistema_luminoso', models.BooleanField(default=False)),
                ('bancos', models.BooleanField(default=False)),
                ('tapetas', models.BooleanField(default=False)),
                ('painel', models.BooleanField(default=False)),
                ('limpeza_interna', models.BooleanField(default=False)),
                ('antena', models.BooleanField(default=False)),
                ('pneus', models.BooleanField(default=False)),
                ('calotas', models.BooleanField(default=False)),
                ('rodas_liga', models.BooleanField(default=False)),
                ('para_brisa', models.BooleanField(default=False)),
                ('palhetas_dianteiras', models.BooleanField(default=False)),
                ('palheta_traseira', models.BooleanField(default=False)),
                ('farois_dianteiros', models.BooleanField(default=False)),
                ('farois_neblina', models.BooleanField(default=False)),
                ('lanternas_traseiras', models.BooleanField(default=False)),
                ('luz_re', models.BooleanField(default=False)),
                ('sensor_estacionamento', models.BooleanField(default=False)),
                ('portinhola_tanque', models.BooleanField(default=False)),
                ('fluido_freio', models.BooleanField(default=False)),
                ('liquido_arrefecimento', models.BooleanField(default=False)),
                ('fluido_direcao', models.BooleanField(default=False)),
                ('bateria', models.BooleanField(default=False)),
                ('amortecedor', models.BooleanField(default=False)),
                ('tampa_porta_malas', models.BooleanField(default=False)),
                ('estepe', models.BooleanField(default=False)),
                ('triangulo', models.BooleanField(default=False)),
                ('chave_rodas', models.BooleanField(default=False)),
                ('macaco', models.BooleanField(default=False)),
                ('suspensao', models.BooleanField(default=False)),
                ('documentacao', models.BooleanField(default=False)),
                ('oleo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_viatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist de Viatura',
                'verbose_name_plural': 'Checklists de Viatura',
                'unique_together': {('usuario', 'data')},
            },
        ),
    ]
