# Generated by Django 5.2.6 on 2025-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0007_checklistviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='talao',
            name='talao_numero',
            field=models.PositiveIntegerField(default=1, help_text='Sequência reinicia a cada plantão', verbose_name='Número seq. no plantão'),
        ),
    ]
