# Generated by Django 5.2.6 on 2025-10-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0008_talao_talao_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisicao_numero', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº da Requisição')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel')], max_length=10, verbose_name='Tipo de Combustível')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Litros')),
                ('recibo_do_posto', models.FileField(blank=True, null=True, upload_to='abastecimentos/%Y/%m/', verbose_name='Recibo do Posto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('talao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='taloes.talao', verbose_name='Talão')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['talao', 'criado_em'], name='taloes_abas_talao_i_aa6a5d_idx')],
            },
        ),
    ]
