# Generated by Django 5.2.6 on 2025-10-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0010_checklist_outros'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvariaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantao_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('data', models.DateField(db_index=True)),
                ('itens_json', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_logs', to='viaturas.viatura')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['data', 'plantao_id'], name='taloes_avar_data_6bed1c_idx')],
            },
        ),
    ]
