# Generated by Django 5.2.6 on 2025-10-16 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0011_avarialog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AitRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da AIT')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('talao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aits', to='taloes.talao', verbose_name='Talão')),
            ],
            options={
                'verbose_name': 'AIT do Talão',
                'verbose_name_plural': 'AITs do Talão',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('talao', 'numero'), name='uniq_talao_numero_ait')],
            },
        ),
    ]
