# Generated by Django 5.2.6 on 2025-10-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0012_aitregistro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitregistro',
            name='integrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aits_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Integrante'),
        ),
    ]
