# Generated by Django 5.2.6 on 2025-11-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taloes', '0013_aitregistro_integrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvariaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_avaria', models.CharField(db_index=True, help_text='Nome do campo de avaria (ex: radio_comunicador, sistema_luminoso)', max_length=100)),
                ('arquivo', models.FileField(help_text='Foto ou arquivo da avaria', upload_to='avarias/%Y/%m/')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='taloes.checklistviatura')),
            ],
            options={
                'verbose_name': 'Anexo de Avaria',
                'verbose_name_plural': 'Anexos de Avarias',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['checklist', 'campo_avaria'], name='taloes_avar_checkli_473bd6_idx')],
            },
        ),
    ]
