# Generated by Django 5.2.6 on 2025-09-12 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('natureza', models.CharField(max_length=120)),
                ('cod_natureza', models.CharField(blank=True, max_length=20)),
                ('solicitante', models.CharField(blank=True, max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('envolvidos', models.TextField(blank=True)),
                ('providencias', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('EDICAO', 'Aberto (edição)'), ('FINALIZADO', 'Finalizado'), ('DESPACHO_CMT', 'Despacho CMT'), ('ARQUIVADO', 'Arquivado')], default='EDICAO', max_length=16)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('edit_deadline', models.DateTimeField(blank=True, null=True)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bos_enc', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bos_motorista', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaturas.viatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenciaBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('valor', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('ano',)},
            },
        ),
    ]
