# Generated by Django 5.2.5 on 2025-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_social', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('condicao', models.CharField(max_length=60)),
                ('outra_condicao', models.CharField(blank=True, max_length=60)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('ponto_referencia', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(default='SP', max_length=2)),
                ('cidade', models.CharField(default='IBIUNA', max_length=60)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=30)),
                ('pais_natural', models.CharField(default='Brasil', max_length=60)),
                ('uf_natural', models.CharField(default='SP', max_length=2)),
                ('cidade_natural', models.CharField(default='IBIUNA', max_length=60)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('outro_documento', models.CharField(blank=True, max_length=60)),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('razao_social', models.CharField(blank=True, max_length=120)),
                ('cnpj', models.CharField(blank=True, max_length=30)),
                ('cnh', models.CharField(blank=True, max_length=30)),
                ('categoria_cnh', models.CharField(blank=True, max_length=10)),
                ('data_validacao_cnh', models.DateField(blank=True, null=True)),
                ('cutis', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('profissao', models.CharField(blank=True, max_length=60)),
                ('trabalho', models.CharField(blank=True, max_length=120)),
                ('vulgo', models.CharField(blank=True, max_length=60)),
                ('nome_pai', models.CharField(blank=True, max_length=120)),
                ('nome_mae', models.CharField(blank=True, max_length=120)),
                ('sinais', models.TextField(blank=True)),
                ('dados_adicionais', models.TextField(blank=True)),
                ('providencia', models.CharField(blank=True, max_length=60)),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='assinaturas/')),
            ],
        ),
    ]
