# Generated by Django 5.2.5 on 2025-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0002_envolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvido',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
