# Generated by Django 5.2.5 on 2025-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0003_envolvido_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envolvido',
            name='cidade',
            field=models.CharField(blank=True, default='IBIUNA', max_length=60),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='cidade_natural',
            field=models.CharField(blank=True, default='IBIUNA', max_length=60),
        ),
        migrations.AlterField(
            model_name='envolvido',
            name='pais_natural',
            field=models.CharField(blank=True, default='Brasil', max_length=60),
        ),
    ]
