# Generated by Django 5.2.5 on 2025-09-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0005_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envolvido',
            name='anexo',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='envolvido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='bogcmi.envolvido'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
