# Generated by Django 5.2.5 on 2025-09-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0006_remove_envolvido_anexo_alter_anexo_envolvido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('destino', models.CharField(max_length=100)),
                ('recebedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoApreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='apreensoes/')),
                ('apreensao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='bogcmi.apreensao')),
            ],
        ),
    ]
