# Generated by Django 5.2.5 on 2025-09-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0007_apreensao_anexoapreensao'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoEnvolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('renavam', models.CharField(blank=True, max_length=20)),
                ('numero_chassi', models.CharField(blank=True, max_length=30)),
                ('numero_motor', models.CharField(blank=True, max_length=30)),
                ('placa_cidade', models.CharField(blank=True, max_length=100)),
                ('placa_estado', models.CharField(default='SP', max_length=2)),
                ('cor', models.CharField(blank=True, max_length=30)),
                ('ano_modelo', models.CharField(blank=True, max_length=4)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=4)),
                ('semaforo', models.CharField(blank=True, choices=[('funcionando', 'Funcionando'), ('nao_funcionando', 'Não Funcionando'), ('intermitente', 'Intermitente'), ('nao_ha', 'Não Há')], max_length=20)),
                ('tipo_pista', models.CharField(blank=True, choices=[('seca', 'Seca'), ('molhada', 'Molhada'), ('oleosa', 'Oleosa'), ('com_lama', 'Com Lama'), ('com_areia', 'Com Areia')], max_length=20)),
                ('tipo_acidente', models.CharField(blank=True, choices=[('colisao_traseira', 'Colisão Traseira'), ('colisao_frontal', 'Colisão Frontal'), ('colisao_lateral', 'Colisão Lateral'), ('abalroamento', 'Abalroamento'), ('capotamento', 'Capotamento'), ('tombamento', 'Tombamento'), ('atropelamento', 'Atropelamento'), ('saida_pista', 'Saída de Pista')], max_length=30)),
                ('tempo', models.CharField(blank=True, choices=[('sol', 'Sol'), ('chuva', 'Chuva'), ('garoa', 'Garoa'), ('nevoeiro', 'Nevoeiro'), ('vento', 'Vento'), ('nublado', 'Nublado')], max_length=20)),
                ('iluminacao', models.CharField(blank=True, choices=[('plena', 'Plena'), ('escuridao', 'Escuridão'), ('amanhecer', 'Amanhecer'), ('anoitecer', 'Anoitecer'), ('iluminacao_publica', 'Iluminação Pública')], max_length=30)),
                ('proprietario', models.CharField(blank=True, max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=25)),
                ('situacao_veiculo', models.CharField(blank=True, choices=[('circulando', 'Circulando'), ('estacionado', 'Estacionado'), ('parado_via', 'Parado na Via'), ('em_manobra', 'Em Manobra'), ('fugiu', 'Fugiu do Local')], max_length=30)),
                ('observacao_situacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='veiculos/')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='bogcmi.veiculoenvolvido')),
            ],
        ),
    ]
