# Generated by Django 5.2.5 on 2025-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0008_veiculoenvolvido_anexoveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='danos_identificados',
            field=models.TextField(blank=True, help_text='Lista de danos separados por vírgula'),
        ),
    ]
