# Generated by Django 5.2.5 on 2025-09-28 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0009_veiculoenvolvido_danos_identificados'),
        ('users', '0003_perfil_assinatura_digital'),
        ('viaturas', '0003_alter_viatura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('gcms', models.ManyToManyField(blank=True, to='users.perfil')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaturas.viatura')),
            ],
        ),
    ]
