# Generated by Django 5.2.5 on 2025-09-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0010_equipeapoio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeapoio',
            name='gcms',
        ),
        migrations.AddField(
            model_name='equipeapoio',
            name='participantes',
            field=models.TextField(default='', help_text='Liste os participantes (GCMs, PMs, Polícia Civil, etc.)'),
        ),
    ]
