# Generated by Django 5.2.5 on 2025-09-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0011_remove_equipeapoio_gcms_equipeapoio_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='categoria_cnh',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='cnh',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='validade_cnh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
