# Generated by Django 5.2.5 on 2025-09-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0012_veiculoenvolvido_categoria_cnh_veiculoenvolvido_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='envolvido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='bogcmi.envolvido'),
        ),
    ]
