# Generated by Django 5.2.5 on 2025-09-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0013_alter_anexo_envolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvido',
            name='bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envolvidos_bo', to='bogcmi.bo'),
        ),
    ]
