# Generated by Django 5.2.5 on 2025-09-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0014_envolvido_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='cidade',
            field=models.CharField(blank=True, default='IBIUNA', max_length=60),
        ),
        migrations.AddField(
            model_name='bo',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bo',
            name='referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bo',
            name='rua',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bo',
            name='uf',
            field=models.CharField(blank=True, default='SP', max_length=2),
        ),
    ]
