# Generated by Django 5.2.5 on 2025-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0015_bo_cidade_bo_numero_endereco_bo_referencia_bo_rua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='documento_html',
            field=models.TextField(blank=True),
        ),
    ]
