# Generated by Django 5.2.5 on 2025-09-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0016_bo_documento_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='apreensao',
            name='bo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apreensoes', to='bogcmi.bo'),
            preserve_default=False,
        ),
    ]
