# Generated by Django 5.2.6 on 2025-09-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0017_apreensao_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexos_gerais', to='bogcmi.bo'),
        ),
        migrations.AddField(
            model_name='equipeapoio',
            name='bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='bogcmi.bo'),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='bogcmi.bo'),
        ),
    ]
