# Generated by Django 5.2.6 on 2025-10-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0018_anexo_bo_equipeapoio_bo_veiculoenvolvido_bo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='auxiliar1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bos_aux1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='auxiliar2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bos_aux2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bo',
            name='cecom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bos_cecom', to=settings.AUTH_USER_MODEL),
        ),
    ]
