# Generated by Django 5.2.6 on 2025-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0019_bo_auxiliar1_bo_auxiliar2_bo_cecom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='duracao',
            field=models.CharField(blank=True, help_text='HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='bo',
            name='horario_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bo',
            name='horario_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bo',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bo',
            name='km_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
