# Generated by Django 5.2.6 on 2025-10-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0020_bo_duracao_bo_horario_final_bo_horario_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bo',
            name='algemas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bo',
            name='autoridade_policial',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bo',
            name='escrivao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bo',
            name='flagrante',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bo',
            name='grande_vulto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bo',
            name='local_finalizacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bo',
            name='numero_bopc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bo',
            name='numero_tco',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
