# Generated by Django 5.2.6 on 2025-10-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bogcmi", "0022_bo_client_uuid_offline"),
    ]

    operations = [
        migrations.AddField(
            model_name="bo",
            name="validacao_hash",
            field=models.CharField(
                blank=True, help_text="Hash interno para integridade", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="bo",
            name="validacao_token",
            field=models.CharField(
                blank=True,
                help_text="Token público para validação do documento",
                max_length=40,
            ),
        ),
    ]
