# Generated by Django 5.2.6 on 2025-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0024_bo_talao'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='apreensao_ait',
            field=models.CharField(blank=True, help_text="Nº das AIT's relacionadas", max_length=120),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='apreensao_crr',
            field=models.CharField(blank=True, help_text='Nº do CRR', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='apreensao_destino',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='veiculoenvolvido',
            name='apreensao_responsavel_guincho',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='bo',
            name='status',
            field=models.CharField(choices=[('EDICAO', 'Aberto (edição)'), ('FINALIZADO', 'Finalizado'), ('DESPACHO_CMT', 'Despacho CMT'), ('CORRIGIR_BO', 'Corrigir BO'), ('ARQUIVADO', 'Arquivado')], default='EDICAO', max_length=16),
        ),
    ]
