# Generated by Django 5.2.6 on 2025-10-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcmi', '0025_veiculoenvolvido_apreensao_ait_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEnvolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_social', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('ponto_referencia', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(blank=True, default='SP', max_length=2)),
                ('cidade', models.CharField(blank=True, default='IBIUNA', max_length=60)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=30)),
                ('pais_natural', models.CharField(blank=True, default='Brasil', max_length=60)),
                ('uf_natural', models.CharField(blank=True, default='SP', max_length=2)),
                ('cidade_natural', models.CharField(blank=True, default='IBIUNA', max_length=60)),
                ('rg', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('cpf_normalizado', models.CharField(db_index=True, max_length=20, unique=True)),
                ('outro_documento', models.CharField(blank=True, max_length=60)),
                ('cnh', models.CharField(blank=True, max_length=30)),
                ('categoria_cnh', models.CharField(blank=True, max_length=10)),
                ('data_validacao_cnh', models.DateField(blank=True, null=True)),
                ('cutis', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('profissao', models.CharField(blank=True, max_length=60)),
                ('trabalho', models.CharField(blank=True, max_length=120)),
                ('vulgo', models.CharField(blank=True, max_length=60)),
                ('nome_pai', models.CharField(blank=True, max_length=120)),
                ('nome_mae', models.CharField(blank=True, max_length=120)),
                ('sinais', models.TextField(blank=True)),
                ('dados_adicionais', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='envolvido',
            name='cadastro',
            field=models.ForeignKey(blank=True, help_text='Cadastro base (auto-preenchimento por CPF).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='bogcmi.cadastroenvolvido'),
        ),
    ]
